services:
  app:
    build:
      context: .
    networks:
      - dokploy-network
    environment:
      - NODE_ENV=production
    restart: unless-stopped

networks:
  dokploy-network:
    external: true
